In [1]:
import numpy as np

In [2]:
zeros=np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [7]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

In [8]:
el = array[1]
print(el)

0.0


In [9]:
array[[4, 2, 0]]

array([1., 1., 0.])

In [10]:

#Assignment:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


In [11]:
##Creating an array from a list with integers:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

In [12]:
#Specifying the type of elements:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [13]:
#np.arange for creating ranges:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [14]:
#Linspace - for creating an array with elements from start till end of a certain size:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
zeros[0] = 300
zeros

array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [16]:
zeros[0] = 300
print(zeros[0])

44


In [17]:
300 % 256

44

In [18]:
#Specify the shape with a tuple:

zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [19]:
print(zeros.shape)


(5, 2)


In [20]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [21]:
print(numbers[0, 1])

2


In [22]:
#Assignment: use a tuple (row index, column index)
numbers[0, 1] = 10

In [23]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
numbers[0]

array([ 1, 10,  3])

In [25]:
#Slicing: getting a column:
numbers[:, 1]

array([10,  5,  8])

In [26]:
#Assigning a row:
numbers[1] = [1, 1, 1]

In [27]:
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [28]:
#Assigning a column:
numbers[:, 2] = [9, 9, 9]

In [29]:
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

In [30]:
#Uniform random numbers between 0 and 1 of shape (5, 2):
np.random.rand(5, 2)

array([[0.50608572, 0.71623622],
       [0.05916901, 0.93486022],
       [0.98247746, 0.30955241],
       [0.59379704, 0.45898558],
       [0.39411344, 0.29679886]])

In [31]:
#Set seed for reproducibility:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [32]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [33]:
#Random integers between 0 and 99 (100 is not included)
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [34]:
#Element-wise operations
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [35]:
#Every item in the array is multiplied by 2:
rng * 2

array([0, 2, 4, 6, 8])

In [36]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

In [37]:
#Adding one array with another
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [38]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [39]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

In [40]:
#Rounding the numbers to 4th digit:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

Two ways to square each element:

element-wise multiplication with itself
the power operator (**)

In [41]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [42]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [43]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

In [44]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [45]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [46]:

np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

In [48]:
#Comparison operations
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [49]:
result = pred >= 0.5
result

array([False, False,  True])

In [50]:
np.random.seed(2)

In [51]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [52]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [53]:
pred1 >= pred2

array([ True, False,  True])

In [54]:

np.random.seed(2)

In [55]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [56]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

In [57]:
#Logical operations
pred1 & pred2

array([ True, False, False])

In [58]:
pred1 | pred2

array([ True,  True,  True])

In [59]:
#Summarizing operations
#Summarizing operations process and array and return a single number
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [60]:
pred_sum

1.02

In [61]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


In [62]:
#For two-dimentional array it works in the same way:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [63]:
matrix.max()

0.62

# But we can specify the axis along which we apply the summarizing operation

axis=1 - apply to each rows

axis=0 - apply to each column

In [64]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [65]:

matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [66]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

In [67]:
#Sorting
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [68]:
#Creaters a new array:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [69]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [70]:
#Sorts in place:
pred.sort()

In [71]:
pred

array([0.03, 0.44, 0.44, 0.55])

In [72]:
#Argsort - instead of sorting, return the indexes of the array in sorted order
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [73]:
idx = pred.argsort()

In [74]:
idx

array([1, 0, 3, 2], dtype=int64)

In [75]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [76]:
#Reshaping
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
rng.shape

(12,)

In [78]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [80]:
#But number of rows x columns should be equal to the total number of elements
rng.reshape(4, 4)


ValueError: cannot reshape array of size 12 into shape (4,4)

In [82]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [83]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

# Putting mulitple arrays together:

concatenate

hstack

vstack

column_stack

In [84]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [86]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [87]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [88]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [89]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [90]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [91]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [92]:
#Transpose
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [93]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

In [94]:
#Slicing
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [95]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [97]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [98]:
mat[[3, 0, 1]]


array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [99]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [100]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [101]:
#Vector-vector multiplication
u = np.array([0, 1, 2])
v = np.array([1, 2, 3])
u.dot(v)

8

In [102]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [103]:
X.dot(u)

array([5, 8, 9])

In [105]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])

In [106]:
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

In [107]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [108]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [109]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:

B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

np.linalg.inv(B)

LinAlgError: Singular matrix

In [111]:
b = np.array([1, 2, 3])

In [112]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [113]:
A.dot(x)

array([1., 2., 3.])

# Vector operations

In [114]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [115]:
# addition 
u + v

# subtraction 
u - v

# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [116]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [117]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [118]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [119]:
I = np.eye(3)

In [120]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)

# Pandas

In [121]:
import pandas as pd
import numpy as np

In [122]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [123]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [124]:
#Alternatively, we can use a list of dictionaries to create a dataframe:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [125]:
df = pd.DataFrame(data)

In [126]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [127]:
df.head(n=2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [128]:
#Columns in a data frame - series. To access it, use dot or brackets
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [129]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [130]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [131]:
col_name = 'Engine HP'
df[col_name]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [132]:
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [133]:
df['id'] = ['nis1', 'hyu1', 'lot2', 'gmc1', 'nis2']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP    id  
0         sedan   2000  nis1  
1         Sedan  27150  hyu1  
2   convertible  54990  lot2  
3       4dr SUV  34450  gmc1  
4        Pickup  32340  nis2

In [134]:
df['id'] = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [135]:
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [136]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [137]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [138]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [139]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: 0, dtype: object

In [140]:
df.iloc[[2, 3, 0]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2   Lotus   Elise  2010      218.0                 4            MANUAL   
3     GMC  Acadia  2017      194.0                 4         AUTOMATIC   
0  Nissan  Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
3       4dr SUV  34450  
0         sedan   2000

In [141]:
idx = np.arange(5)
idx

array([0, 1, 2, 3, 4])

In [143]:
np.random.seed(2)
np.random.shuffle(idx)
idx

array([2, 4, 1, 3, 0])

In [144]:
df.iloc[idx]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

In [145]:
df.iloc[idx]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

In [146]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [147]:
df.iloc[[0, 1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990

In [148]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [149]:
df.loc[[0, 1]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [150]:
df.iloc[[0, 1]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [151]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [152]:
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [153]:
#Splitting data
n_train = 3
n_val = 1
n_test = 1

In [154]:
df_train = df.iloc[:n_train]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

In [155]:
df[['Make', 'Model', 'Year']]

Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

In [156]:
df_train[['Make', 'Model', 'Year']]

Make   Model  Year
0   Nissan  Stanza  1991
1  Hyundai  Sonata  2017
2    Lotus   Elise  2010

In [157]:
df_val[['Make', 'Model', 'Year']]

Make   Model  Year
3  GMC  Acadia  2017

In [158]:
df_test[['Make', 'Model', 'Year']]

Make     Model  Year
4  Nissan  Frontier  2017

In [159]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [160]:
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [161]:
df = df.reset_index(drop=True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [162]:
#Element-wise operations
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [163]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [164]:
df['Year']

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [165]:
df['Year'] > 2000

0    False
1     True
2     True
3     True
4     True
Name: Year, dtype: bool

In [166]:
df['Make'] == 'Nissan'

0     True
1    False
2    False
3    False
4     True
Name: Make, dtype: bool

In [167]:
(df['Year'] > 2000) & (df['Make'] == 'Nissan')

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [168]:
df[df['Make'] == 'Nissan']

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [169]:
df[(df['Year'] > 2010) & (df['Transmission Type'] == 'AUTOMATIC')]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450

In [170]:
#String operations
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [171]:

df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [172]:
df['Vehicle_Style'].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [173]:
df['Vehicle_Style'].str.lower().str.replace(' ', '_')

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

In [174]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [175]:
df.columns.str.lower().str.replace(' ', '_')

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp'],
      dtype='object')

In [176]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [177]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  vehicle_style   msrp  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [178]:
df.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders       int64
transmission_type     object
vehicle_style         object
msrp                   int64
dtype: object

In [179]:
df.dtypes.index

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp'],
      dtype='object')

In [180]:
df.dtypes == 'object'

make                  True
model                 True
year                 False
engine_hp            False
engine_cylinders     False
transmission_type     True
vehicle_style         True
msrp                 False
dtype: bool

In [181]:
df.dtypes[df.dtypes == 'object']

make                 object
model                object
transmission_type    object
vehicle_style        object
dtype: object

In [182]:
df.dtypes[df.dtypes == 'object'].index

Index(['make', 'model', 'transmission_type', 'vehicle_style'], dtype='object')

In [183]:
list(df.dtypes[df.dtypes == 'object'].index)

['make', 'model', 'transmission_type', 'vehicle_style']

In [184]:
string_columns = df.dtypes[df.dtypes == 'object'].index

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [185]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [186]:
#Numerical columns
df.msrp

0     2000
1    27150
2    54990
3    34450
4    32340
Name: msrp, dtype: int64

In [187]:
df.msrp.mean()

30186.0

In [188]:
df.msrp.sum()

150930

In [189]:
df.msrp.min(), df.msrp.max(), df.msrp.mean(), df.msrp.std()

(2000, 54990, 30186.0, 18985.044903818372)

In [190]:
df.msrp.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: msrp, dtype: float64

In [191]:
df.mean()

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


year                 2010.40
engine_hp             202.75
engine_cylinders        4.40
msrp                30186.00
dtype: float64

In [192]:

df.describe().round(2)

year  engine_hp  engine_cylinders      msrp
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [193]:
df.make.nunique()

4

In [194]:

df.nunique()

make                 4
model                5
year                 3
engine_hp            4
engine_cylinders     2
transmission_type    2
vehicle_style        4
msrp                 5
dtype: int64

In [195]:
df.make.value_counts()

nissan     2
hyundai    1
lotus      1
gmc        1
Name: make, dtype: int64

In [196]:
#Missing values
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [197]:
df.isnull()

make  model   year  engine_hp  engine_cylinders  transmission_type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   vehicle_style   msrp  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [198]:

df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            1
engine_cylinders     0
transmission_type    0
vehicle_style        0
msrp                 0
dtype: int64

In [199]:

df.engine_hp.isnull()

0    False
1     True
2    False
3    False
4    False
Name: engine_hp, dtype: bool

In [200]:

df.engine_hp.fillna(0)

0    138.0
1      0.0
2    218.0
3    194.0
4    261.0
Name: engine_hp, dtype: float64

In [201]:

df.engine_hp.fillna(df.engine_hp.mean())

0    138.00
1    202.75
2    218.00
3    194.00
4    261.00
Name: engine_hp, dtype: float64

In [202]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [203]:
df.engine_hp = df.engine_hp.fillna(df.engine_hp.mean())
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [204]:
#Sorting and re-ordering
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [205]:
df.sort_values(by='msrp')

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
4        pickup  32340  
3       4dr_suv  34450  
2   convertible  54990

In [206]:
df.sort_values(by='msrp')

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
4        pickup  32340  
3       4dr_suv  34450  
2   convertible  54990

# Grouping

In [208]:
df.groupby('transmission_type').msrp.mean()

transmission_type
automatic    30800.000000
manual       29776.666667
Name: msrp, dtype: float64

In [209]:
df.groupby('transmission_type').msrp.agg(['mean', 'count'])

mean  count
transmission_type                     
automatic          30800.000000      2
manual             29776.666667      3

In [210]:
df.groupby('transmission_type').msrp.agg(['mean', 'count'])

mean  count
transmission_type                     
automatic          30800.000000      2
manual             29776.666667      3

In [211]:
df_group = df.groupby('transmission_type').msrp.agg(['mean', 'count'])
df_group

mean  count
transmission_type                     
automatic          30800.000000      2
manual             29776.666667      3

In [212]:
df_group['mean'] - df.msrp.mean()

transmission_type
automatic    614.000000
manual      -409.333333
Name: mean, dtype: float64

In [213]:
df.msrp

0     2000
1    27150
2    54990
3    34450
4    32340
Name: msrp, dtype: int64

In [214]:
np.log1p(df.msrp)

0     7.601402
1    10.209169
2    10.914925
3    10.447293
4    10.384091
Name: msrp, dtype: float64

In [215]:
df.msrp.values

array([ 2000, 27150, 54990, 34450, 32340], dtype=int64)

In [216]:
np.log1p(df.msrp.values)

array([ 7.60140233, 10.20916916, 10.91492481, 10.4472933 , 10.38409105])

In [217]:
#Convert to dicts
df.to_dict(orient='rows')

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  


[{'make': 'nissan',
  'model': 'stanza',
  'year': 1991,
  'engine_hp': 138.0,
  'engine_cylinders': 4,
  'transmission_type': 'manual',
  'vehicle_style': 'sedan',
  'msrp': 2000},
 {'make': 'hyundai',
  'model': 'sonata',
  'year': 2017,
  'engine_hp': 202.75,
  'engine_cylinders': 4,
  'transmission_type': 'automatic',
  'vehicle_style': 'sedan',
  'msrp': 27150},
 {'make': 'lotus',
  'model': 'elise',
  'year': 2010,
  'engine_hp': 218.0,
  'engine_cylinders': 4,
  'transmission_type': 'manual',
  'vehicle_style': 'convertible',
  'msrp': 54990},
 {'make': 'gmc',
  'model': 'acadia',
  'year': 2017,
  'engine_hp': 194.0,
  'engine_cylinders': 4,
  'transmission_type': 'automatic',
  'vehicle_style': '4dr_suv',
  'msrp': 34450},
 {'make': 'nissan',
  'model': 'frontier',
  'year': 2017,
  'engine_hp': 261.0,
  'engine_cylinders': 6,
  'transmission_type': 'manual',
  'vehicle_style': 'pickup',
  'msrp': 32340}]